### ISSUE TITLE
/tp @s positon doesn't work

### ISSUE THREAD

**Issue by REver0** [DogLoverPink/EssentialsX-Target-Selectors#5]
**What went wrong?**
 Player command  /tp @s 10 12 10 doesn't work, still shows "player not found", but the command /tp @s can work
When I was playing on "CatServer-1.12.2" trying to use the command "/tp @s 100 50 100" or the mods XaerosWorldMap, Xaeros_Minimap's funcation "Teleport Here" I still got "player not found". Please help fix that!
**Steps for recreation:**
    1. install CatServer with plugins ess. and mods XaerosWorldMap, Xaeros_Minimap
    2.connect the CatServer, 
    3.type in the chat blank "tp @s 10 20 20" press enter you will see "player not found" (not just this three number, any position is ok)
    4.pree M to open the full screen map right click on the map, choose "Teleport Here" you will got "player not found" in the chat
      PS the order of 3 & 4 doesn't matter 
**Any errors in console? If so, post the full error here, or post it on [this](https://mclo.gs/) website and share the link.**
 
**What is your plugin, server, and java version?**
**The plugin version is:**
    EssentialsSelectors-v1.6
    EssentialsX-2.19.5-dev+20-8d856dd
    EssentialsXAntiBuild-2.19.5-dev+20-8d856dd
    EssentialsXChat-2.19.5-dev+20-8d856dd
    EssentialsXProtect-2.19.5-dev+20-8d856dd
    EssentialsXSpawn-2.19.5-dev+20-8d856ddx
    GroupManager-2.9
    spark-1.8.19-bukkit
    Vault-1.7.3
**The server is** : CatServer-1.12.2
The java edtion is :  1.8.0_321
 
**Anything else?**

**Comment by DogLoverPink** [comment]
Hey Rever0, unfortunatly this issue is related specifically to catserver, as it works fine on normal 1.12.2 (just tested). While I will do some debugging in an attempt to find the cause, it is very likely that this will never be fixed, as it is an issue on catserver's end. I, and basically all plugin developers can't really support forge hybrids such as this one, as they change Bukkit slighty, meaning that alot of things will break.

**Comment by DogLoverPink** [comment]
This is a catServer issue and not a plugin issue, so there isn't really anything I can do, sorry. Thank you for reporting tho!
